#!/usr/bin/env bash
set -e

echo "--- format check ---"
clojure -M:cljfmt check

echo "--- tests ---"
#clojure -M:dev:test // TODO: re-enable tests once we have a better story for running them in CI

echo "✅ All checks passed"
